server {
    listen 80; # Тот самый порт 80 для Render

    location / {
        root /app/public; # Раздаем статику фронтенда
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://localhost:8080; # Проксируем запросы к бэкенду
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    # Не забудь про маршруты редиректов, если они есть
    location /r/ {
        proxy_pass http://localhost:8080;
    }
}